baseURL = "http://localhost:1313/"
languageCode = "zh"
defaultContentLanguage = "zh"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "EilenC"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "PaperMod"
enableGitInfo = false # use git commit log to generate lastmod record # å¯æ ¹æ® Git ä¸­çš„æäº¤ç”Ÿæˆæœ€è¿‘æ›´æ–°è®°å½•ã€‚

# Syntax highlighting by Chroma. NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

hasCJKLanguage = true     # has chinese/japanese/korean ? # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡\æ—¥æ–‡\éŸ©æ–‡
paginate = 5                                              # é¦–é¡µæ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name â†“        # é»˜è®¤ä¸ºä¸‹é¢é…ç½®çš„author.name â†“

[author]                  # essential                     # å¿…éœ€
  name = "EilenC"

[sitemap]                 # essential                     # å¿…éœ€
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # é…ç½®ç›®å½•
  name = "ä¸»é¡µ"
  weight = 1
  url = "/"
[[menu.main]]
  name = "å½’æ¡£"
  weight = 2
  url = "/archives/"
[[menu.main]]
  name = "æ ‡ç­¾"
  weight = 3
  url = "/tags/"
[[menu.main]]
  name = "åˆ†ç±»"
  weight = 4
  url = "/categories/"
[[menu.main]]
  name = "About"
  weight = 5
  url = "/about/"
[[menu.main]]
  name = "Search"
  weight = 6
  url = "/search/"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
dateFormat = "2006-01-02"
dateTimeFormat = "2006-01-02 15:04"
ShowShareButtons = true #æ˜¾ç¤ºæ–‡ç« åˆ†äº«æŒ‰é’®
ShowReadingTime = true # æ˜¾ç¤ºå¤§è‡´é˜…è¯»æ—¶é—´
ShowWordCount = true # æ˜¾ç¤ºå­—æ•°
ShowToc = true #é¡¶éƒ¨ç›®å½•
TocOpen = true #å§‹ç»ˆæ‰“å¼€é¡¶éƒ¨ç›®å½•
ShowCodeCopyButtons = true #æ˜¾ç¤ºä»£ç å»å¿«å¤åˆ¶æŒ‰é’®
PagePrevText = "Prev"
PageNextText = "Next"

[params.homeInfoParams]
Content = "# Hi thereğŸ‘‹\n\n- ğŸŒ± Iâ€™m currently learning programming."
Describe = "#### Languages & Tools"
Icons = "https://skillicons.dev/icons?i=go,php,kotlin,java,spring,tensorflow,pytorch,rust,docker,haskell,kubernetes,zig&theme=light"
IconSize = "40px"